[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
automod = "1"
color-eyre = "0.6"
itertools = "0.10"
linkme = "0.3"
ndarray = { version = "0.15", features = ["rayon"] }
regex = "1"
